### ISSUE TITLE
Installing commands are not working

### ISSUE THREAD

**Issue by GitHunter0** [prise6/R-dygraphs-sync#1]
Hey @prise6 , your solution is a great contribution!

Unfortunately, I am not managing to install the package from that other branch and follow the instructions you provided. Please, can you provide some updated step by step?

`$ git pull origin pull/197/head:master`
returns this message:
```
From https://github.com/rstudio/dygraphs
 ! [rejected]        refs/pull/197/head -> master  (non-fast-forward)
```
Then
```
 lib.tmp = "~/tmp_lib"
withr::with_libpaths(new  = lib.tmp, devtools::install_github("timelyportfolio/dygraphs_htmlwidget"))
```
returns:
`Error: Failed to install 'dygraphs' from GitHub`

Thank you very much

**Comment by prise6** [comment]
Hi,
This solution could be outdated now. To my understanding, PR [#197](https://github.com/rstudio/dygraphs/pull/197) should have fixed the original issue. Therfore, you should have access to the original dygraph object thanks to :

```
HTMLWidgets.getInstance()
HTMLWidgets.find()
HTMLWidgets.findAll()
```
The code i provide at the end should work out of the box. If not, try to spot the problem and open an issue in dygraph repo.

Hope it helps.

**Comment by GitHunter0** [comment]
@prise6  Hey man, it is indeed working with the last Github version, thank you very much, this feature is awesome!

Just three last things if I may:
(1) Although the cursor is synchronized, the zoom is not, it kind of breaks/distorts the graphs, which it is pity since zoom is an important feature. Is there a solution to that? 

(2) How can this synchronization feature be used inside Shiny (which is my ultimate goal)? 

(3) "synchronized.plugin.js" still only works making the replacement `var idx = gs[i].findClosestRow(gs[i].toDomXCoord(x));`. Future release of R dygraphs will make it work out of the box?

**Comment by prise6** [comment]
(1): see in [synchronize](https://github.com/danvk/dygraphs/blob/master/src/extras/synchronizer.js) plugin, there are three options (selection, zoom and range):

```js
Dygraph.synchronize(dygraphsCollection, {selection : true, zoom: true, range: true});
```
it should work (not tested)

(2) Dirty way is to do how i did. I mean included `synchronized.plugin.js` as html dependency. And then create a script to call this plugin. Have a look [here](https://shiny.rstudio.com/articles/packaging-javascript.html) and to go futher [here](https://shiny.rstudio.com/articles/communicating-with-js.html).
Cleanest way should be to create a plugin to dygraph r package, like [this](https://rstudio.github.io/dygraphs/gallery-plugins.html).

(3) This problem is linked to dygraph javascript library (original lib). Nobody opened an issue about this... So even if dygraph r package updates the dygraph javascript lib, issue will still be there i guess.

**Comment by GitHunter0** [comment]
Thank you very much for the clarifications, I managed to make things work! 
OBS: It required to set selection and zoom to true but **range to false**. 
Cheers @prise6
